[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/add-user"
  status = 200

[[redirects]]
  from = "/api/farms"
  to = "/.netlify/functions/handle-farms-route"
  status = 200

[[redirects]]
  from = "/api/farms/:farmId"
  to = "/.netlify/functions/handle-farms-route/farms/:farmId"
  status = 200

[[redirects]]
  from = "/api/farms/:farmId/ponds"
  to = "/.netlify/functions/handle-ponds-route/farms/:farmId"
  status = 200
